---
output: github_document
bibliography: vignettes/bibliography.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

# Predicting graph structure from a time series of graphs

If you have a time series of dynamic graphs that change structure, how would you predict future graphs? This is the goal of netseer.  

Netseer predicts the graph structure including new nodes and edges from a time series of graphs. It adapts Flux Balance Analysis, a method used in metabolic network reconstruction to predict the structue of future graphs. The methodology is explained in the preprint [@kand2025graphpred]. 


## R package
The algorithm is available in both R and Python. The R package `netseer` in on CRAN and can be installed as follows:

``` r
install_packages("netseer")
```

The vignette for the R package is available under [Get Started.](articles/netseer.html) 

## Python code

The Python code is available at https://github.com/sevvandi/netseer-python/. The Python package will be made available in the near future. 

## Coding Credits
A big shout out to Stefan Westerlund and Brodie Oldfield for helping with this package. Stefan optimized the algorithm in R and coded it from scratch in Python. Brodie is currently packaging up the Python code and is working on a website for the Python version. 

## References
